markdown: kramdown
title: DE Software
description: Designing and customizing everything from Websites, Chat Bots, and Cross Platform Software. Our objective is multipurpose, multi-platform and to bring quality of life to our clients and users.
logo: social.jpg
discord: https://discord.gg/RPRPeCe
email: contact.de.software@gmail.com

collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"

collections:
  staff: